CASMCMS-7676 Add support for recipes with template params
Cray-HPE/ims-python-helper pull request #4
Opened 2022-02-08 21:30 UTC by ecozzi-hpe

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

Enable IMS python helper to add recipes to IMS that include a template-dictionary

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)](https://github.com/Cray-HPE/ims-python-helper/tree/CASMCMS-7676)

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

Enable IMS python helper to add recipes to IMS that include a template-dictionary

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)](https://github.com/Cray-HPE/ims-python-helper/tree/CASMCMS-7676)

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-02-17 16:30 UTC, rkleinman-hpe requested changes

2022-02-17 16:30 UTC, rkleinman-hpe commented on ims_python_helper/__init__.py
> +    def recipe_upload(self, name, filepath, distro, template_dictionary):
Will this be a major revision? This is a backward incompatible change. Also, missing explanation of this new arg in the docstring below (line 375ish)

2022-02-17 16:30 UTC, rkleinman-hpe commented on ims_python_helper/__init__.py
> +            'template_dictionary': template_dictionary,
Hopefully no one puts any sensitive information in this field. Maybe worth a disclaimer in docs that this data is available to anyone with access to the IMS API.

2022-02-17 16:47 UTC, ecozzi-hpe commented on ims_python_helper/__init__.py
> +    def recipe_upload(self, name, filepath, distro, template_dictionary):
Good catch. I'll make the extra parameter optional and conditionalize its use elsewhere.

2022-02-17 16:47 UTC, ecozzi-hpe commented on ims_python_helper/__init__.py
> +            'template_dictionary': template_dictionary,
Yeah, this is not meant for sensitive information.

2022-02-17 18:57 UTC, rkleinman-hpe approved these changes

2022-05-13 00:11 UTC, mharding-hpe approved these changes

2022-05-23 20:36 UTC, closed without merging